Merge the current master branch, bringing the faces branch up-to-date

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Copyright 2009-2013 Yorba Foundation
+# Copyright 2009-2015 Yorba Foundation
 #
 # This software is licensed under the GNU LGPL (version 2.1 or later).
 # See the COPYING file in this distribution.
@@ -8,42 +8,53 @@
 CONFIG_IN=configure.mk
 
 configure_help() {
-    printf "\nUsage:\n"
-    printf "\t./configure [OPTIONS]...\n"
-    printf "\n"
-    printf "Options:\n"
-    printf "\t-h, --help\t\tPrint this help and exit.\n"
-    printf "\t--enable-tests\t\tEnable Shotwell to run automated tests.\n"
-    printf "\t--enable-faces\t\tEnable Faces Tool.\n"
-    printf "\t--assume-pkgs\t\tTurn off package version checking.\n"
-    printf "\t--build=DIR\t\tBuild secondary files in DIR.\n"
-    printf "\t--debug | --release\tBuild executable for debugging or release.\n"
-    printf "\t\t\t\t[--release]\n"
-    printf "\t--prefix=PREFIX\t\tPrepend PREFIX to program installation paths.\n"
-    printf "\t\t\t\t[/usr/local]\n"
-    printf "\t--lib=LIBNAME\t\tSet system library directory name to LIBNAME\n\t\t\t\t(usually 'lib' or 'lib64').\n"
-    printf "\t\t\t\t[lib]\n"
-    printf "\t--define=SYMBOL\t\tDefine a symbol for the Vala compiler.\n"
-    printf "\n\n"
-    printf "\t--disable-schemas-compile\n"
-    printf "\t\t\t\tDisable compiling the GSettings schema.\n"
-    printf "\t--disable-gsettings-convert-install\n"
-    printf "\t\t\t\tDisable installing the gsettings-data-convert file.\n"
-    printf "\t--disable-desktop-update\n"
-    printf "\t\t\t\tDisable desktop database update.\n"
-    printf "\t--disable-icon-update\n"
-    printf "\t\t\t\tDisable icon cache update.\n"
-    printf "\t--enable-build-for-glade\n"
-    printf "\t\t\t\tEnable build for Glade-related development.\n"
-    printf "\t--disable-help-install\n"
-    printf "\t\t\t\tDisable installation of online help.\n"
-    printf "\t--disable-extra-plugins-install\n"
-    printf "\t\t\t\tDisable installation of extra (non-core) plugins.\n"
-    printf "\t--install-headers\n"
-    printf "\t\t\t\tInstall headers and VAPI files (developers only).\n"
-    printf "\t--unity-support\n"
-    printf "\t\t\t\tEnable support for progress bars in the Unity launcher.\n"
-    printf "\n"
+    cat <<- EOT
+Usage:
+    ./configure [OPTIONS]...
+
+Options:
+    -h, --help              Print this help and exit.
+    --assume-pkgs           Turn off package version checking.
+    --build=DIR             Build secondary files in DIR.
+    --debug | --release	    Build executable for debugging or release.
+                            [--release]
+    --profile               Enable profiling support during C compile & link.
+    --prefix=PREFIX         Prepend PREFIX to program installation paths.
+                            [/usr/local]
+    --lib=LIBNAME           Set system library directory name to LIBNAME
+                            (usually 'lib' or 'lib64').
+                            [lib]
+    --libdir LIBNAME        Equivalent to --lib=LIBNAME
+    --libexec=LIBEXECDIR    Set utility executable to LIBEXECDIR
+                            (usually 'PREFIX/libexec/shotwell').
+                            [PREFIX/libexec/shotwell]
+    --libexec LIBEXECDIR    Equivalent to --libexec=LIBEXECDIR
+
+    --define=SYMBOL         Define a symbol for the Vala compiler.
+    
+    --enable-faces          Enable Faces Tool.
+	
+    --disable-schemas-compile
+                            Disable compiling the GSettings schema.
+    --disable-gsettings-convert-install
+                            Disable installing the gsettings-data-convert file.
+    --disable-desktop-update
+                            Disable desktop database update.
+    --disable-desktop-validate
+                            Disable validation of .desktop files.
+    --disable-icon-update
+                            Disable icon cache update.
+    --enable-build-for-glade
+                            Enable build for Glade-related development.
+    --disable-help-install
+                            Disable installation of online help.
+    --disable-extra-plugins-install
+                            Disable installation of extra (non-core) plugins.
+    --install-headers
+                            Install headers and VAPI files (developers only).
+    --unity-support
+                            Enable support for progress bars in the Unity launcher.
+EOT
 }
 
 abort() {
@@ -67,18 +78,29 @@ do
         
         --prefix)           if [ ! $value ]
                             then
-                                abort $1
+                                shift
+                                value=$1
                             fi
                             
                             variables="${variables}PREFIX=$value\n"
                             ;;
 
-        --lib)              if [ ! $value ]
+        --lib | --libdir)   if [ ! $value ]
                             then
-                                abort $1
+                                shift
+                                value=$1
                             fi
                             
                             variables="${variables}LIB=$value\n"
+                            ;;
+
+        --libexec)          if [ ! $value ]
+                            then
+                                shift
+                                value=$1
+                            fi
+                            
+                            variables="${variables}LIBEXECDIR=$value\n"
                             ;;
 
         --assume-pkgs)      variables="${variables}ASSUME_PKGS=1\n"
@@ -86,13 +108,17 @@ do
         
         --build)            if [ ! $value ]
                             then
-                                abort $1
+                                shift
+                                value=$1
                             fi
                             
                             variables="${variables}BUILD_DIR=$value\n"
                             ;;
         
         --debug)            variables="${variables}BUILD_RELEASE=\nBUILD_DEBUG=1\n"
+                            ;;
+        
+        --profile)          variables="${variables}PROFILE_FLAGS=-pg\n"
                             ;;
         
         --release)          variables="${variables}BUILD_DEBUG=\nBUILD_RELEASE=1\n"
@@ -110,15 +136,18 @@ do
         --disable-desktop-update)         variables="${variables}DISABLE_DESKTOP_UPDATE=1\n"
                                           ;;
 
+        --disable-desktop-validate)       variables="${variables}DISABLE_DESKTOP_VALIDATE=1\n"
+                                          ;;
+
         --disable-icon-update)            variables="${variables}DISABLE_ICON_UPDATE=1\n"
                                           ;;
 
         --enable-build-for-glade)         variables="${variables}ENABLE_BUILD_FOR_GLADE=1\n"
                                           ;;
-        --enable-tests)                   variables="${variables}ENABLE_TESTS=1\n"
-                                          ;;
+
         --enable-faces)                   variables="${variables}ENABLE_FACES=1\n"
                                           ;;
+
         --disable-help-install)           variables="${variables}DISABLE_HELP_INSTALL=1\n"
                                           ;;
         --disable-extra-plugins-install)  variables="${variables}DISABLE_EXTRA_PLUGINS_INSTALL=1\n"
@@ -129,6 +158,11 @@ do
         
         --unity-support)                  variables="${variables}UNITY_SUPPORT=1\n"
                                           ;;
+        
+        --enable-* | --disable-*)
+        
+                            echo WARNING: unrecognized option: $option
+                            ;;
         
         *)                  if [ `echo $option | grep '\-\-'` ]
                             then
@@ -149,7 +183,14 @@ done
 pkg-config --atleast-version 2.5 libgphoto2
 if [ $? == 1 ]
 then 
-    printf "Detected libGPhoto 2.4.x - using default code path.\n";
+    pkg-config --atleast-version 2.4 libgphoto2
+    if [ $? == 1 ]
+    then
+        printf "No compatible libGPhoto installation found. Configuration cannot continue.\n";
+        exit 1
+    else
+        printf "Detected libGPhoto 2.4.x - using default code path.\n";
+    fi
 else
     printf "Detected libGPhoto 2.5.x - using 2.5-aware code path.\n";
     variables="${variables}WITH_GPHOTO_25=1\n"
